name:                dstoken-forwarder-contract
version:             0.1.0.0
github:              "tqtezos/dstoken-forwarder-contract"
license:             MIT
author:              "Michael J. Klein"
maintainer:          "michael@tqgroup.io"
copyright:           "2019-2020 Michael J. Klein, TQ Tezos"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tqtezos/dstoken-forwarder-contract#readme>

flags:
  dstoken:
    description: Include DS Token
    manual: true
    default: false

dependencies:
- base >= 4.7 && < 5
- morley
- lorentz
- named
- singletons
- text
- constraints
- morley-ledgers
- morley-nettest
- morley-upgradeable
- constraints
- containers
- universum
- vinyl

when:
- condition: flag(dstoken)
  then:
    cpp-options: -DHAS_DSTOKEN
    dependencies:
    - morley-dstoken
  else:
    cpp-options: -DNO_DSTOKEN

library:
  source-dirs: src

executables:
  dstoken-forwarder-contract:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dstoken-forwarder-contract
    - morley
    - morley-nettest
    - fmt
    - optparse-applicative
    - random
    - universum
    when:
    - condition: flag(dstoken)
      then:
        cpp-options: -DHAS_DSTOKEN
        dependencies:
        - morley-dstoken
      else:
        cpp-options: -DNO_DSTOKEN

tests:
  dstoken-forwarder-contract-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dstoken-forwarder-contract
    - fmt
    - hspec
    - tasty
    - tasty-hspec
    - tasty-discover
